## Pandas Homework 1:

In [ ]:
# Homework 1:
import pandas as pd

data = {'First Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)

# Task 1
# Change table name in dataframe

df.rename(columns={
    'First Name': 'first name',
    'Age' : 'age'

}, inplace= True)

df

  first name  age           City
0      Alice   25       New York
1        Bob   30  San Francisco
2    Charlie   35    Los Angeles
3      David   40        Chicago

In [9]:
# task 2
# print top 3 rows in DataFrame
df.head(3)

  first name  age           City
0      Alice   25       New York
1        Bob   30  San Francisco
2    Charlie   35    Los Angeles

In [ ]:
# Task 3 
# find avrage age of individuals
df['age'].mean()

  first name  age           City
0      Alice   25       New York
1        Bob   30  San Francisco
2    Charlie   35    Los Angeles
3      David   40        Chicago

In [20]:
# Task 4
#Select and print only the 'Name' and 'City' columns

df[['first name','age']]

  first name  age
0      Alice   25
1        Bob   30
2    Charlie   35
3      David   40

In [23]:
# task 5
# Add a new column 'Salary' with random salary values

df['Salary']= df['age'] * 100
df['Salary']
df

  first name  age           City  Salary
0      Alice   25       New York    2500
1        Bob   30  San Francisco    3000
2    Charlie   35    Los Angeles    3500
3      David   40        Chicago    4000

In [24]:
# Display summary statistics of the DataFrame

df.describe()

             age       Salary
count   4.000000     4.000000
mean   32.500000  3250.000000
std     6.454972   645.497224
min    25.000000  2500.000000
25%    28.750000  2875.000000
50%    32.500000  3250.000000
75%    36.250000  3625.000000
max    40.000000  4000.000000

## Homework 2:

In [33]:
import pandas as pd

data = {'Month': ['Jan','Feb','Mar','Apr'],
        'Sales': [5000,6000,7500,8000],
        'Expenses': [3000,3500,4000,4500]}

sales_and_expenses = pd.DataFrame(data)
sales_and_expenses

  Month  Sales  Expenses
0   Jan   5000      3000
1   Feb   6000      3500
2   Mar   7500      4000
3   Apr   8000      4500

In [38]:
#Calculate and display the maximum sales and expenses.
sales_and_expenses[['Sales','Expenses']].max()

Sales       8000
Expenses    4500
dtype: int64

In [76]:
# Calculate and display the minimum sales and expenses.
sales_and_expenses[['Sales','Expenses']].min()

Sales       5000
Expenses    3000
dtype: int64

In [41]:
# Calculate and display the average sales and expenses.
sales_and_expenses[['Sales','Expenses']].mean()

Sales       6625.0
Expenses    3750.0
dtype: float64

## Homework 3

In [42]:
# Homework 3
# task 1

import pandas as pd

data = {'Category': ['Rent','Utilities','Groceries','Entertainment'],
        'January': [1200,200,300,150],
        'February': [1300,220,320,160],
        'March':[1400,240,330,170],
        'April':[1500,250,350,180]}

h3_df = pd.DataFrame(data)
h3_df

        Category  January  February  March  April
0           Rent     1200      1300   1400   1500
1      Utilities      200       220    240    250
2      Groceries      300       320    330    350
3  Entertainment      150       160    170    180

In [57]:
# task 2
# Calculate and display the maximum expense for each category.

h3_df['Max_expenses']=h3_df[['January', 'February', 'March', 'April']].max(axis=1)
h3_df[['Category','Max_expenses']]

        Category  Max_expenses
0           Rent          1500
1      Utilities           250
2      Groceries           350
3  Entertainment           180

In [58]:
# task 3
# Calculate and display the minimum expense for each category.

h3_df['Min_Expenses'] = h3_df[['January', 'February', 'March', 'April']].min(axis=1)
h3_df[['Category','Min_Expenses']]

        Category  Min_Expenses
0           Rent          1200
1      Utilities           200
2      Groceries           300
3  Entertainment           150

In [71]:
# task 4
# Calculate and display the average expense for each category.

h3_df['Avrage_Expenses'] = h3_df[['January', 'February', 'March', 'April']].mean(axis=1)
h3_df[['Category','Avrage_Expenses']]
h3_df

,Category,January,February,March,April,Max_expenses,Min_Expenses,Avrage_Expenses
0,Rent,1200,1300,1400,1500,1500,1200,1350.0
1,Utilities,200,220,240,250,250,200,227.5
2,Groceries,300,320,330,350,350,300,325.0
3,Entertainment,150,160,170,180,180,150,165.0

In [75]:
expenses = h3_df.set_index('Category')
expenses

,January,February,March,April,Max_expenses,Min_Expenses,Avrage_Expenses
Category,,,,,,,
Rent,1200,1300,1400,1500,1500,1200,1350.0
Utilities,200,220,240,250,250,200,227.5
Groceries,300,320,330,350,350,300,325.0
Entertainment,150,160,170,180,180,150,165.0